name: Build and Deploy LearnLM Tutor

on:
  pull_request:
    branches: [prod] # now working, for while
  push:
    branches: [prod] # now working, for while

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: us-central1
  IMAGE_TAG_STREAMLIT_UI: gcr.io/${{ secrets.GCP_PROJECT_ID }}/learnLMtutor:${{ github.sha }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        install_components: 'beta'

    - name: Verify gcloud configuration
      run: |
        gcloud config list
        gcloud info

    - name: Submit build to Cloud Build
      run: |
        gcloud builds submit \
          --config cloudbuild.yaml \
          --substitutions=IMAGE_TAG_STREAMLIT_UI=$IMAGE_TAG_STREAMLIT_UI
    
    - name: Deploy API to Cloud Run
      run: |-
        gcloud run deploy ${{ secrets.SERVICE_NAME }} \
          --image ${{ env.IMAGE_TAG_STREAMLIT_UI }} \
          --platform managed \
          --region "$RUN_REGION" \
          --allow-unauthenticated \
          --timeout=300s \
          --set-env-vars "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}"
  